In [ ]:
import bigframes as bf
import bigframes.pandas as bpd

In [ ]:
# Fechar a sessão atual
bf.pandas.close_session()

# Configurar o projeto e a localização
bf.options.bigquery.project = "bdcc2024-416116"
bf.options.bigquery.location = "US"

**LOADING THE INITIAL DATASETS**

In [ ]:
df = bpd.read_gbq("bdcc2024-416116.cdle.CHARTEVENTS")
df

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,CGID,VALUE,VALUENUM,VALUEUOM,WARNING,ERROR,RESULTSTATUS,STOPPED
0,89665332,10724,164826,231067,3652,2185-06-10 15:30:00,2185-06-10 16:15:00,16660,98,98,Deg F,<NA>,<NA>,<NA>,NotStopd
1,271155005,40548,168670,260223,223901,2156-08-09 08:00:00,2156-08-09 12:43:00,19463,Obeys Commands,6,<NA>,0,0,<NA>,<NA>
2,85506333,9960,159243,200036,550,2181-08-29 03:00:00,2181-08-29 04:02:00,18592,Universal,<NA>,<NA>,<NA>,<NA>,<NA>,NotStopd
3,183524860,30310,121631,282905,171,2108-11-16 17:00:00,2108-11-16 19:45:00,15630,Cough/DeepBreath,<NA>,<NA>,<NA>,<NA>,<NA>,NotStopd
4,74709283,7731,125193,287285,32,2178-02-28 01:00:00,2178-02-28 03:25:00,21570,Tolerated Well,<NA>,<NA>,<NA>,<NA>,<NA>,NotStopd
5,161747143,25368,146404,233582,618,2128-09-17 17:00:00,2128-09-17 17:02:00,15283,24,24,BPM,<NA>,<NA>,<NA>,NotStopd
6,224304991,31044,184171,204730,5820,2121-05-04 19:00:00,2121-05-04 19:11:00,16302,90,90,%,<NA>,<NA>,<NA>,NotStopd
7,24361814,78532,177956,240761,224150,2159-05-08 03:00:00,2159-05-08 06:45:00,17574,176,176,mmHg,0,0,<NA>,<NA>
8,54287556,3868,157650,269518,211,2125-09-13 07:00:00,2125-09-13 07:30:00,17189,87,87,BPM,<NA>,<NA>,<NA>,NotStopd
9,135859715,19942,190227,213176,683,2164-07-27 12:00:00,2164-07-27 12:04:00,18795,500,500,ml/B,<NA>,<NA>,<NA>,NotStopd
10,252578470,29127,150613,263686,8554,2139-05-14 00:00:00,2139-05-14 00:03:00,17219,100,100,%,<NA>,<NA>,<NA>,NotStopd
11,183897009,30396,125706,236168,159,2180-08-20 01:00:00,2180-08-20 01:15:00,18469,None,<NA>,<NA>,<NA>,<NA>,<NA>,NotStopd
12,78191,665,170157,281431,220339,2119-05-16 12:00:00,2119-05-16 12:32:00,19101,8,8,cmH2O,0,0,<NA>,<NA>
13,11984826,53463,183511,246549,223876,2178-08-09 04:00:00,2178-08-09 04:10:00,19747,20,20,sec,0,0,<NA>,<NA>
14,9789709,48732,196123,224097,220045,2105-11-13 13:00:00,2105-11-13 13:09:00,17250,91,91,bpm,0,0,<NA>,<NA>
15,9554387,48297,103539,230670,224738,2163-06-25 20:00:00,2163-06-25 19:17:00,14371,.8,.8,sec,0,0,<NA>,<NA>
16,159827078,24974,178757,210203,80,2135-02-14 04:00:00,2135-02-14 05:50:00,15996,Active,<NA>,<NA>,<NA>,<NA>,<NA>,NotStopd
17,295514213,64538,127392,228387,224370,2105-02-27 20:00:00,2105-02-27 19:57:00,18999,White,<NA>,<NA>,0,0,<NA>,<NA>
18,40170847,1075,190552,243588,211,2175-02-18 13:00:00,2175-02-18 13:57:00,20781,119,119,BPM,<NA>,<NA>,<NA>,NotStopd
19,239759195,14945,110433,293148,8548,2138-03-17 11:00:00,2138-03-17 11:01:00,19089,20,20,mmHg,<NA>,<NA>,<NA>,NotStopd
20,124921560,17746,131077,276814,3580,2142-06-01 04:30:00,2142-06-01 05:34:00,14425,3.0750000476837158,3.0750000476837158,kg,<NA>,<NA>,<NA>,NotStopd
21,1278811,11993,115213,238732,220210,2186-12-15 09:00:00,2186-12-15 09:07:00,16102,14,14,insp/min,0,0,<NA>,<NA>
22,314301582,83180,196309,244255,224087,2188-01-08 14:00:00,2188-01-08 14:00:00,17735,AtmosAir Mattress,<NA>,<NA>,0,0,<NA>,<NA>
23,257968568,58871,114864,207932,227292,2197-12-16 00:10:00,2197-12-16 00:10:00,16284,1,1,<NA>,0,0,<NA>,<NA>
24,225351508,32253,156847,279303,440,2137-07-22 07:00:00,2137-07-22 07:14:00,16356,6,6,<NA>,<NA>,<NA>,<NA>,NotStopd

In [ ]:
df2 = bpd.read_gbq("bdcc2024-416116.cdle.ICUSTAYS")
df2

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,DBSOURCE,FIRST_CAREUNIT,LAST_CAREUNIT,FIRST_WARDID,LAST_WARDID,INTIME,OUTTIME,LOS
0,11127,8744,175078,230090,carevue,NICU,NICU,56,56,2137-01-22 22:20:47+00:00,2137-01-23 00:57:15+00:00,0.1087
1,5359,4223,122294,227863,carevue,MICU,MICU,52,52,2152-04-07 20:05:14+00:00,2152-04-09 18:04:39+00:00,1.9163
2,59268,93362,187375,234826,metavision,CSRU,CSRU,12,12,2134-01-18 10:56:44+00:00,2134-01-19 15:48:39+00:00,1.2027
3,5045,3977,111024,203161,carevue,MICU,MICU,15,15,2141-05-04 18:55:56+00:00,2141-05-06 17:33:04+00:00,1.9425
4,9239,7255,180181,293531,carevue,CCU,CCU,57,57,2173-06-21 14:21:11+00:00,2173-06-25 19:00:47+00:00,4.1942
5,23434,18490,166658,211034,carevue,MICU,MICU,50,50,2105-07-23 03:50:56+00:00,2105-07-24 15:02:32+00:00,1.4664
6,46837,56116,131774,254007,metavision,TSICU,TSICU,14,14,2121-01-22 14:29:09+00:00,2121-01-23 18:01:45+00:00,1.1476
7,53805,76736,113085,212477,metavision,MICU,MICU,52,52,2168-03-26 03:04:39+00:00,2168-03-26 19:43:53+00:00,0.6939
8,3703,2948,158914,263205,carevue,MICU,MICU,12,12,2129-11-12 00:21:25+00:00,2129-11-14 18:06:28+00:00,2.7396
9,36184,28557,178081,296366,carevue,CSRU,CSRU,15,12,2129-05-18 11:22:43+00:00,2129-05-19 10:51:58+00:00,0.9786
10,1315,1010,128495,229123,carevue,MICU,MICU,52,23,2179-05-07 06:34:44+00:00,2179-05-08 18:35:59+00:00,1.5009
11,52070,71527,118552,203970,metavision,SICU,SICU,57,57,2141-10-04 12:26:58+00:00,2141-10-05 11:31:09+00:00,0.9612
12,2243,1778,126694,213469,carevue,MICU,MICU,52,52,2129-07-06 01:18:24+00:00,2129-07-16 19:26:46+00:00,10.7558
13,43577,46733,170387,202706,metavision,SICU,TSICU,57,14,2101-12-29 20:51:33+00:00,2102-01-02 20:23:51+00:00,3.9808
14,29868,23582,105770,203633,carevue,CCU,CCU,7,7,2197-12-01 12:00:44+00:00,2197-12-02 17:28:14+00:00,1.2274
15,6224,4917,190071,288592,carevue,CSRU,CSRU,14,14,2175-03-16 11:07:08+00:00,2175-03-19 17:25:28+00:00,3.2627
16,38948,30788,120198,282982,carevue,NICU,NICU,56,56,2193-11-14 10:43:23+00:00,2193-11-16 14:59:38+00:00,2.178
17,1307,1006,189081,209730,carevue,SICU,SICU,57,57,2159-05-19 16:07:18+00:00,2159-05-23 19:06:22+00:00,4.1244
18,27969,22063,186846,250161,carevue,TSICU,TSICU,14,14,2151-06-30 14:08:10+00:00,2151-07-01 18:46:03+00:00,1.193
19,54170,77804,102018,228189,metavision,SICU,SICU,33,33,2102-06-17 13:14:50+00:00,2102-06-19 18:05:17+00:00,2.2017
20,18556,14617,132697,287150,carevue,MICU,MICU,52,52,2111-10-01 20:20:56+00:00,2111-10-02 22:21:44+00:00,1.0839
21,33788,26634,169063,219965,carevue,NICU,NICU,56,56,2141-03-19 04:34:12+00:00,2141-03-20 09:02:22+00:00,1.1862
22,24325,19176,197312,212591,carevue,NICU,NICU,56,56,2128-03-25 03:08:00+00:00,2128-03-25 05:30:00+00:00,0.0986
23,40105,31791,189622,217948,carevue,TSICU,TSICU,14,14,2127-08-19 19:23:36+00:00,2127-08-23 23:56:11+00:00,4.1893
24,8037,6317,122673,273720,carevue,MICU,MICU,52,52,2138-08-07 18:59:25+00:00,2138-08-20 10:17:21+00:00,12.6375

In [ ]:
df3 = bpd.read_gbq("bdcc2024-416116.cdle.DIAGNOSES_ICD")
df3

    ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0   436671       52592   136506        6      4111
1   365507       31765   194985        1      9941
2   219842       19689   180660        6     41401
3   224476       20124   148251        2      5856
4   503588       67069   104665       15       412
5   287989       25724   196248        1     41001
6   323810       28531   170966        7     57400
7    61192        5476   100343        5     51881
8   373988       32426   103254       21     V4364
9   192812       17288   123138        7     49390
10  551611       77676   170561        8       496
11   63892        5709   130207        3     42731
12  211753       19026   168469        3      7706
13  210685       18946   160113        8      7470
14  637927       97037   129694       20     79902
15  568948       81564   161743        9     E8781
16  526760       72197   130412       19     V4582
17  599713       88711   197264        2      2860
18  121362       10814   141996        6      2851
19   37922        3402   135170        7      7793
20  126746       11294   143748        3     25001
21  387338       41830   118355       13     V5865
22  321550       28358   158829        1     55221
23   49030        4392   171423       13     25060
24  368841       32025   170481       14     V4582
...

[651047 rows x 5 columns]

In [ ]:
df5 = bpd.read_gbq("bdcc2024-416116.cdle.PATIENTS")
df5

,ROW_ID,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG
0,33252,49367,F,2092-03-30 00:00:00+00:00,<NA>,<NA>,<NA>,0
1,2642,2793,F,1887-04-13 00:00:00+00:00,2187-04-18 00:00:00+00:00,2187-04-18 00:00:00+00:00,2187-04-18 00:00:00+00:00,1
2,23066,24444,M,2104-09-05 00:00:00+00:00,2168-09-03 00:00:00+00:00,2168-09-03 00:00:00+00:00,2168-09-03 00:00:00+00:00,1
3,15423,16312,M,2118-09-24 00:00:00+00:00,<NA>,<NA>,<NA>,0
4,29140,31000,F,2099-01-04 00:00:00+00:00,2176-11-16 00:00:00+00:00,2176-11-16 00:00:00+00:00,2176-11-16 00:00:00+00:00,1
5,37722,66109,F,2103-12-15 00:00:00+00:00,<NA>,<NA>,<NA>,0
6,38364,68601,F,2118-11-23 00:00:00+00:00,<NA>,<NA>,<NA>,0
7,37341,64752,F,1862-06-23 00:00:00+00:00,<NA>,<NA>,<NA>,0
8,8597,9083,M,2153-10-30 00:00:00+00:00,<NA>,<NA>,<NA>,0
9,18105,19170,F,2145-03-18 00:00:00+00:00,<NA>,<NA>,<NA>,0
10,11258,11897,F,2051-08-16 00:00:00+00:00,2123-07-18 00:00:00+00:00,<NA>,2123-07-18 00:00:00+00:00,1
11,985,1041,M,2116-03-11 00:00:00+00:00,<NA>,<NA>,<NA>,0
12,44309,91490,M,1810-09-02 00:00:00+00:00,<NA>,<NA>,<NA>,0
13,23548,24953,M,2135-06-09 00:00:00+00:00,<NA>,<NA>,<NA>,0
14,19036,20169,F,2123-12-22 00:00:00+00:00,<NA>,<NA>,<NA>,0
15,7087,7488,M,2112-10-15 00:00:00+00:00,<NA>,<NA>,<NA>,0
16,14684,15532,F,2169-11-18 00:00:00+00:00,<NA>,<NA>,<NA>,0
17,42153,83202,F,2113-06-14 00:00:00+00:00,<NA>,<NA>,<NA>,0
18,10696,11315,M,2108-12-08 00:00:00+00:00,<NA>,<NA>,<NA>,0
19,15256,16136,M,2084-10-13 00:00:00+00:00,2167-09-25 00:00:00+00:00,<NA>,2167-09-25 00:00:00+00:00,1
20,4370,4618,M,2123-06-15 00:00:00+00:00,2205-05-23 00:00:00+00:00,2205-05-23 00:00:00+00:00,2205-05-23 00:00:00+00:00,1
21,44458,92013,F,2057-02-23 00:00:00+00:00,<NA>,<NA>,<NA>,0
22,22878,24239,M,2089-03-18 00:00:00+00:00,2153-07-12 00:00:00+00:00,2153-07-12 00:00:00+00:00,2153-07-12 00:00:00+00:00,1
23,8773,9273,M,2093-06-03 00:00:00+00:00,2148-08-09 00:00:00+00:00,<NA>,2148-08-09 00:00:00+00:00,1
24,15427,16316,M,2146-04-10 00:00:00+00:00,<NA>,<NA>,<NA>,0

In [ ]:
df6 = bpd.read_gbq("bdcc2024-416116.cdle.ADMISSIONS")
df6

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,13085,10699,131811,2185-05-31 10:20:00+00:00,2185-07-11 12:15:00+00:00,<NA>,NEWBORN,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Private,<NA>,CATHOLIC,<NA>,WHITE,<NA>,<NA>,NEWBORN,0,1
1,5542,4587,198345,2150-05-19 11:01:00+00:00,2150-05-21 15:01:00+00:00,2150-05-21 15:01:00+00:00,EMERGENCY,EMERGENCY ROOM ADMIT,DEAD/EXPIRED,Medicare,<NA>,CATHOLIC,MARRIED,WHITE,2150-05-19 03:19:00+00:00,2150-05-19 10:45:00+00:00,SEPSIS;HYPOXIA,1,1
2,28638,23467,101328,2169-08-02 17:08:00+00:00,2169-08-04 16:14:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,<NA>,JEWISH,<NA>,WHITE,<NA>,<NA>,NEWBORN,0,1
3,27285,22362,148514,2117-01-21 12:54:00+00:00,2117-01-28 13:20:00+00:00,<NA>,NEWBORN,CLINIC REFERRAL/PREMATURE,SHORT TERM HOSPITAL,Medicaid,<NA>,PROTESTANT QUAKER,<NA>,WHITE,<NA>,<NA>,NEWBORN,0,1
4,51357,76116,170491,2164-10-08 12:36:00+00:00,2164-10-12 16:30:00+00:00,<NA>,EMERGENCY,CLINIC REFERRAL/PREMATURE,LONG TERM CARE HOSPITAL,Private,ENGL,PROTESTANT QUAKER,MARRIED,BLACK/AFRICAN AMERICAN,2164-10-08 08:40:00+00:00,2164-10-08 13:05:00+00:00,STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK,0,1
5,35700,29277,111703,2167-10-17 11:15:00+00:00,2167-10-19 13:15:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Government,ENGL,CHRISTIAN SCIENTIST,SINGLE,BLACK/AFRICAN AMERICAN,<NA>,<NA>,NEWBORN,0,1
6,25534,20925,133360,2139-04-02 07:15:00+00:00,2139-04-15 13:20:00+00:00,<NA>,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,<NA>,PROTESTANT QUAKER,MARRIED,WHITE,<NA>,<NA>,BLADDER CA/SDA,0,1
7,9568,7809,149867,2133-01-07 04:14:00+00:00,2133-01-11 16:58:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicaid,ENGL,PROTESTANT QUAKER,DIVORCED,BLACK/AFRICAN AMERICAN,2133-01-06 23:22:00+00:00,2133-01-07 05:54:00+00:00,DIABETIC KETOACIDOSIS,0,1
8,7252,5921,128142,2159-01-01 01:51:00+00:00,2159-01-11 19:03:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicaid,CAPE,<NA>,SINGLE,UNKNOWN/NOT SPECIFIED,2159-01-01 00:06:00+00:00,2159-01-01 02:30:00+00:00,S/P MOTOR VEHICLE ACCIDENT,0,1
9,36849,30253,170829,2150-08-20 12:02:00+00:00,2150-08-26 13:42:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,2150-08-20 09:08:00+00:00,2150-08-20 13:28:00+00:00,HYPOGLYCEMIA,0,1
10,31148,25467,197320,2156-12-04 12:20:00+00:00,2156-12-12 10:57:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,ENGL,CATHOLIC,SINGLE,WHITE,<NA>,<NA>,NEWBORN,0,1
11,5794,4787,189443,2125-10-16 17:21:00+00:00,2125-10-23 14:27:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,SNF,Medicare,ENGL,JEWISH,MARRIED,WHITE,2125-10-16 12:06:00+00:00,2125-10-16 18:06:00+00:00,SEPSIS,0,1
12,20761,16984,117392,2124-08-11 22:13:00+00:00,2124-08-14 18:00:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,<NA>,EPISCOPALIAN,<NA>,WHITE,<NA>,<NA>,NEWBORN,0,1
13,18588,15209,191888,2128-12-24 13:29:00+00:00,2129-01-04 15:45:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Private,<NA>,CATHOLIC,MARRIED,WHITE,2128-12-24 09:16:00+00:00,2128-12-24 12:44:00+00:00,ENTEROCUTANEOUS FISTULA,0,1
14,12371,10119,157466,2117-08-05 18:27:00+00:00,2117-08-19 16:15:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,2117-08-05 12:10:00+00:00,2117-08-05 19:48:00+00:00,ACUTE CHOLECYSTITIS,0,1
15,3075,2541,147135,2160-12-20 18:57:00+00:00,2161-01-31 11:40:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,SHORT TERM HOSPITAL,Private,<NA>,CATHOLIC,<NA>,WHITE,<NA>,<NA>,NEWBORN,0,1
16,6669,5484,149871,2136-04-25 16:14:00+00:00,2136-05-08 15:30:00+00:00,<NA>,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,<NA>,UNOBTAINABLE,<NA>,UNKNOWN/NOT SPECIFIED,<NA>,<NA>,NEWBORN,0,1
17,28386,23258,196695,2195-07-21 23:01:00+00:00,2195-07-28 00:21:00+00:00,2195-07-28 00:21:00+00:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Medicare,<NA>,PROTESTANT QUAKER,MARRIED,WHITE,<NA>,<NA>,"STROKE,ENDOCARDITIS",1,1
18,25813,21151,169387,2193-03-26 19:57:00+00:00,2193-04-29 15:44:00+00:00,<NA>,EMERGENCY,CLINIC REFERRAL/PREMATURE,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,SINGLE,WHITE,2193-03-26 19:05:00+00:00,2193-03-26 20:58:00+00:00,ALTERED MENTAL STATUS,0,1
19,4826,3979,126329,2185-06-07 07:15:00+00:00,2185-06-14 17:00:00+00:00,<NA>,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicaid,ENGL,CATHOLIC,SINGLE,WHITE,<NA>,<NA>,MITRAL REGURGITATION\MINIMALLY INVASIVE MITRAL...,0,1
20,18503,15128,112441,2162-05-01 20:38:00+00:00,2162-05-05 20:00:00+00:00,<NA>,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,<NA>,CATHOLIC,MARRIED,WHITE,2162-05-01 19:50:00+00:00,2162-05-01 22:04:00+00:00,UPPER GIB,0,0
21,3103,2562,100290,2116-05-29 17:09:00+00:00,2116-06-11 16:25:00+00:00,<NA>,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,SNF,Medicare,<NA>,OTHER,DIVORCED,UNKNOWN/NOT SPECIFIED,<NA>,<NA>,CORONARY ARTERY DISEASE,0,1
22,53865,83802,133440,2170-01-04 16:01:00+00:00,2170-01-14 13:36:00+00:00,<NA>,EMERGENCY,PHYS REFERRAL/NORMAL DELI,HOME,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,<NA>,<NA>,DRUG ELUTING CORONARY ARTERY STENT,0,1
23,54944,87450,136481,2197-07-25 10:49:00+00:00,2197-08-09 13:00:00+00:00,<NA>,EMERGENCY,CLINIC REFERRAL/PREMATURE,REHAB/DISTINCT PART HOSP,Medicare,SPAN,CATHOLIC,SINGLE,HISPANIC/LATINO - CUBAN,2197-07-25 09:05:00+00:00,2197-07-25 11:48:00+00:00,STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK,0,1
24,5980,4935,166829,2119-01-19 21:11:00+00:00,2119-02-09 16:35:00+00:00,<NA>,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Private,<NA>,PROTESTANT QUAKER,MARRIED,WHITE,<NA>,<NA>,CONGESTIVE HEART FAILURE;NON Q WAVE MYOCARDIAL...,0,1

In [ ]:
df7 = bpd.read_gbq("bdcc2024-416116.cdle.PROCEDURES_ICD")
df7

    ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM  ICD9_CODE
0     3697       15934   161329        3       3961
1   177308       91665   128236        8       9904
2   143085       32420   137514        2       4513
3     4363       23976   171485        6       3893
4    42760        1573   152099        1       3601
5   105330       13259   130325        2       9671
6   105855       32256   192015        1        640
7    35926       24723   145196        3       5472
8    22011       13705   128966        1        331
9   210962       84394   115729        4       9604
10  114888       20966   126366       11       3893
11  172868       55105   100116        1       9604
12   35388        3146   114303        2       9983
13  124539       23363   184040        3       9671
14  137882       31111   139443        9       4513
15   15530        3893   109500        5       9604
16  235449       79285   138379        7       2319
17  233836       71365   167344        7       3961
18    7873       18419   116798        6       3761
19   21448         905   150569        7       9925
20   90430        3997   109247        1       3522
21  193793       98639   167385        6       3781
22  140673       76641   107130        7       8622
23  160567       29080   181664        2       9905
24  190341       63507   164485        6       8856
...

[240095 rows x 5 columns]